Spanish language from english lang
LukeWasTakenn/luke_garages pull request #127
Opened 2022-10-24 17:13 UTC by ItsLincon

That a pull request to merge spanish language into script

2022-10-24 18:28 UTC, LukeWasTakenn requested changes
Please don't delete the english locale file.

2022-10-25 13:56 UTC, icecubepiso commented
is this Spanish invasion ?

2022-10-25 21:23 UTC, ItsLincon commented
Yesn't

2022-10-26 11:41 UTC, LukeWasTakenn approved these changes

2022-10-26 11:41 UTC, merged