Deleting vehicles server-side
LukeWasTakenn/luke_garages pull request #36
Opened 2022-01-09 09:48 UTC by boostless

2022-01-09 12:52 UTC, LukeWasTakenn requested changes

2022-01-09 12:52 UTC, LukeWasTakenn commented on client/client.lua
> +            TriggerServerEvent('luke_garages:SaveVehicle', vehProps, health, VehToNet(vehicle))
Why remove the vehPlate param?

2022-01-09 12:52 UTC, LukeWasTakenn commented on server/server.lua
> +AddEventHandler('luke_garages:SaveVehicle', function(vehicle, health, plate, ent)
`ent` will be nil because you aren't sending the vehPlate param anymore

2022-01-10 19:52 UTC, LukeWasTakenn commented
Any update on this?

2022-01-10 21:33 UTC, boostless commented
Going to push an update tomorrow

2022-01-10 22:04 UTC, LukeWasTakenn commented
> Going to push an update tomorrow. Utilizing new nh-context, vehicle deletion

I don't want new nh-context, I was actually considering switching over to zf-context

2022-01-11 05:16 UTC, boostless commented
Could do that cause i thinks is just an export change

2022-01-11 07:23 UTC, LukeWasTakenn commented
> Could do that cause i thinks is just an export change

I could be wrong but iirc it actually uses the exact same event and export names so it should just work out of the box...?

2022-01-11 18:40 UTC, boostless commented
Added missing vehicle plate

2022-01-11 19:24 UTC, merged

2022-01-11 19:24 UTC, LukeWasTakenn commented
Thank you